name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build:
    name: "Build ${{ matrix.platform }}"
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
        build_type: [Release]

    env:
      PARALLEL: -j 2
    runs-on: "${{ matrix.platform }}"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - if: ${{ matrix.platform == 'ubuntu-latest' }}
      name: Install headers
      run: |
        sudo apt-get update
        sudo apt install xorg-dev

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cmake -E make_directory ${{github.workspace}}/viewer/assets

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build internal
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build_type }} ${{ env.PARALLEL }}

